export const RoutesUrls = {
  mon: 'https://edu.gov.kg/',
  root: `/${import.meta.env.VITE_BASE}/`,
  login: `/${import.meta.env.VITE_BASE}/login`,
  logout: `/${import.meta.env.VITE_BASE}/logout`,
  notFound: `/${import.meta.env.VITE_BASE}/not-found`,
  generalInfo: `/${import.meta.env.VITE_BASE}/general-info`,
  specialities: `/${import.meta.env.VITE_BASE}/specialities`,
  admissionPlan: `/${import.meta.env.VITE_BASE}/admission-plan`,
  admissionPlanList: `/${import.meta.env.VITE_BASE}/admission-plan-list`,
  admissionCommission: `/${import.meta.env.VITE_BASE}/admission-commission`,
  grantCommission: `/${import.meta.env.VITE_BASE}/grant-commission`,
  attestat: `/${import.meta.env.VITE_BASE}/attestat`,
  recommend: `/${import.meta.env.VITE_BASE}/recommend-candidate`,
  confirmCandidate: `/${import.meta.env.VITE_BASE}/confirm-candidate`,
  searchByPin: `/${import.meta.env.VITE_BASE}/search-by-pin`,
  registerAbiturient: `/${import.meta.env.VITE_BASE}/register-abiturient`,
  instruction: `/${import.meta.env.VITE_BASE}/instruction`,
};
