export const RoutesUrls = {
  mon: 'https://edu.gov.kg/',
  root: `/`,
  login: `/login`,
  cabinet: `/cabinet`,
  main: `/cabinet/main`,
  faculty: `/cabinet/faculty`,
  direction: `/cabinet/direction`,
  specialty: `/cabinet/specialty`,
  disciplines: `/cabinet/disciplines`,
  employees: `/cabinet/employees`,
  curriculum: `/cabinet/curriculum`,
  graduates: `/cabinet/graduates`,
  grades: `/cabinet/grades`,
  organization: `/cabinet/organization`,
  reports: `/cabinet/reports`,
  settings: `/cabinet/settings`,
  help: `/cabinet/help`,
  privacyPolicy: `/cabinet/privacyPolicy`,
  manual: `/cabinet/manual`,
  logout: `/cabinet/logout`,
  notFound: `/not-found`,

  personalInfo: '/cabinet/personal-info',
  selectSpuz: '/cabinet/select-spuz',
  viewRegistrations: '/cabinet/registrations',
  tours: '/cabinet/tours',
  instruction: '/cabinet/instruction',
};
